/**
 * Centralized view-to-owner mapping, auto-populated from git history.
 *
 * DO NOT EDIT MANUALLY — regenerated by scripts/update-view-owners.js
 * Run: npm run update:view-owners
 *
 * Each key is "moduleSlug/viewId" and the value is the display name of the
 * person who first introduced that view's component file.
 *
 * This mapping is also consumed by the org-pulse chatbot integration.
 * Admin overrides from data/view-owner-overrides.json are merged in during generation.
 */
export const viewOwners = {
  // team-tracker
  'team-tracker/home':                             'Dipanshu Gupta',
  'team-tracker/jira-taxonomy':                    'Alex Corvin',
  'team-tracker/manage':                           'Alex Corvin',
  'team-tracker/manager-dashboard':                'Alex Corvin',
  'team-tracker/org-dashboard':                    'Alex Corvin',
  'team-tracker/org-explorer':                     'Dipanshu Gupta',
  'team-tracker/people':                           'Dipanshu Gupta',
  'team-tracker/person-detail':                    'Dipanshu Gupta',
  'team-tracker/reports':                          'Alex Corvin',
  'team-tracker/team-detail':                      'Alex Corvin',
  'team-tracker/unassigned':                       'Alex Corvin',

  // upstream-pulse
  'upstream-pulse/dashboard':                      'Dipanshu Gupta',
  'upstream-pulse/insights':                       'Dipanshu Gupta',
  'upstream-pulse/org-detail':                     'Dipanshu Gupta',
  'upstream-pulse/portfolio':                      'Dipanshu Gupta',
  'upstream-pulse/project-detail':                 'Dipanshu Gupta',
  'upstream-pulse/strategy':                       'Dipanshu Gupta',

  // ── Sub-tab owners (module/view/tab) ──
  // These override the view-level owner when a specific tab is active.

  // team-tracker > manage
  'team-tracker/manage/data-quality':              'Alex Corvin',
  'team-tracker/manage/field-options':             'Alex Corvin',
  'team-tracker/manage/fields':                    'Alex Corvin',
  'team-tracker/manage/teams':                     'Alex Corvin',

  // ── Report owners (module/view/reportId) ──
  // These override the view-level owner when a specific report is selected.

  // team-tracker > reports
  'team-tracker/reports/team-comparison':          'Alex Corvin',
  'team-tracker/reports/trends':                   'Alex Corvin',
}

/**
 * Look up the owner of a view, with optional sub-view granularity.
 * Supports both ?tab= and ?report= query params as sub-view identifiers.
 * Resolution order: sub-view-specific override > sub-view-specific default >
 *                   view-level override > view-level default.
 * @param {string} moduleSlug
 * @param {string} viewId
 * @param {Object} [overrides] - Admin overrides from view-owner-overrides.json
 * @param {string} [subView] - Active sub-view id (tab or report from query params)
 * @returns {string | null} Display name of the owner
 */
export function getViewOwner(moduleSlug, viewId, overrides = {}, subView = null) {
  const viewKey = `${moduleSlug}/${viewId}`
  if (subView) {
    const subKey = `${viewKey}/${subView}`
    if (overrides[subKey]) return overrides[subKey]
    if (viewOwners[subKey]) return viewOwners[subKey]
  }
  return overrides[viewKey] || viewOwners[viewKey] || null
}
